---
- name: Playbook to install Docker and run Docker application image
  hosts: build_servers
  become: yes
  tasks:

    - name: Update the apt cache
      apt:
        update_cache: yes

    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install dependencies for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
        filename: docker

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Install Docker Python module via apt
      apt:
         name: python3-docker
         state: present


    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Log in to Docker Hub
      docker_login:
          username: preethiadmin
          password: Chintu_2023

    - name: Pull Docker image from Docker Hub
      docker_image:
          name: preethiadmin/addressbookimage
          source: pull


    - name: Run the Docker container
      docker_container:
        name: container01
        image: preethiadmin/addressbookimage
        state: started
        ports:
          - "8080:80"  # Map host port 8080 to container port 80, adjust as needed
        volumes:
          - "/host/path:/container/path"  # Optional: Map volume from host to container
        restart_policy: always

